name: CI

on:
  push:
    branches: [ main , dev] 
  pull_request:
    branches: [ main , dev] 

  workflow_dispatch: 

jobs:
  build:
    runs-on: alpine

    steps:
      - uses: actions/checkout@v2

      - name: Build AVR
        run: bash CI/build.sh
