name: CI

on:
  push:
    branches: [ main , dev] 
  pull_request:
    branches: [ main , dev] 

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build AVR
        run: bash CI/build.sh

      - name: Artifact Compiled main.hex 
        uses: actions/upload-artifact@v2
        with:
          name: Compiled hex
          path: main.hex

      - name: Artifact Compiled main.bin 
        uses: actions/upload-artifact@v2
        with:
          name: Compiled bin
          path: main.bin

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            main.bin
            main.hex
