name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    steps:
       uses: jjveldscholten/arm_riot_toolchain:latest
       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Building Code
        run: |
          avr-gcc -Wall -g -Os -mmcu=attiny85 -o main.bin main.c,
          avr-objcopy -j .text -j .data -O ihex main.bin main.hex.
        
