name: CI

on:
  push:
    branches: [ main , dev] 
  pull_request:
    branches: [ main , dev] 

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build AVR
        run: bash CI/build.sh

      - name: Artifact Compiled main.hex 
        uses: actions/upload-artifact@v2
        with:
          name: Compiled hex
          path: main.hex

      - name: Artifact Compiled main.bin 
        uses: actions/upload-artifact@v2
        with:
          name: Compiled bin
          path: bin.hex
